### ISSUE TITLE
RFE : writing connected state for monitoring purpose

### ISSUE THREAD

**Issue by arrfab** [repoSpanner/repoSpanner#15]
Actually, /var/lib/repospanner/state/state.json contains some informations about peers in the cluster, but nothing about connection state in that cluster.
Would be good to add it so that it can be monitored (and that state.json can be used for that, and parsed through some monitoring tools like Zabbix or others)

**Comment by puiterwijk** [comment]
Monitoring is now part of nodestate.
There's a sane exit code, and there's also a `--nagios` for nagios-style output.
