### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by bkabrda** [repoSpanner/repoSpanner#29]
While trying to set up repoSpanner for my Pagure instance, I'm having a hard time while debugging what I did wrong, since error messages don't contain the source of the error. For example on sending a wrong request trying to create a repo, I just get "Error parsing request". Looking at the code [1], this might have been caused by two different issues, but I can't really tell which one of them.

Another case is using repobridge, which will just say "Error initializing bridge" without any further info. It would be much better if it included information from `extra` argument to `exitWithError` [2] to make debugging easier.

I find that having better error messages would be much more useful than having more documentation, because people are always going to do mistakes when trying to set things up and seeing clear messages would help a lot with that. I guess there are other places where this could be improved, these are just the ones that I've hit so far.

[1] https://github.com/repoSpanner/repoSpanner/blob/68d8c1354537759ebfe301ccdf198867341aff15/server/service/http-admin.go#L47
[2] https://github.com/repoSpanner/repoSpanner/blob/1a38753b60b35ac0c75ae258f0239a364ac815cb/bridge/root.go#L61

**Comment by puiterwijk** [comment]
I've added 41a92247b9a27cb985790ec916c074ce890c29ca and fdc75a7c55719f93773ed7624a7fb35a2c66b866 for the specific errors you pointed out.
I'll try to add more logging in interesting places as well, if you come across any other examples, let me know.

**Comment by bkabrda** [comment]
Thank you very much, I will definitely let you know if I find more places that need improvements.
