### ISSUE TITLE
New repos not being created

### ISSUE THREAD

**Issue by bkabrda** [repoSpanner/repoSpanner#30]
I'm trying to use repospanner (1 node only, running in container) and I can't figure out how to create a repository. Repospanner seems to initialize correctly (I see no errors in logs) and when I issue an admin/createrepo API call, I get a "200" response `{"Success":true,"Error":"","Info":""}`. The node emits a message "Repo creation requested", but the repo can't be checked out and is not in the storage directory specified in the config.

I'm running repospanner with `--debug`, so I don't believe I can provide more logs. What would you need to help me debug this issue? Thanks!

**Comment by arrfab** [comment]
from the home page here on github : "repoSpanner is a distributed repository storage server, based around Git.

It is designed so that all nodes are equal -- any client can push/pull to/from any node and should see no difference at all. Each node makes sure that all pushed objects are synced to at least a majority of the nodes before acknowledging the push."

So with only one node, it's not a real cluster and so you need at least two to be able to use repoSpanner :)

**Comment by bkabrda** [comment]
@arrfab I don't see how the referenced information implies that more than one node is strictly necessary, but I'll give it a try. Thanks!

**Comment by puiterwijk** [comment]
@bkabrda Is the client certificate you use authorized to access the repository you created?
Admin permissions only grant access to the API, *not* to actual git actions on the repository.

Please provide `openssl x509 -in $clientcert -noout -text` as that will tell that.

When you create the leaf cert, make sure you grant it access to the correct repos.
Perhaps by `--region '*' --repo '*'`.

**Comment by puiterwijk** [comment]
Also, the fact that it's not in the git storage directory is correct: that only gets created on first push to the repo.

**Comment by bkabrda** [comment]
Output of `openssl x509 -in $clientcert -noout -text` (this is the cert that I pass to repobridge via `REPOBRIDGE_CERT` environment variable):

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 2 (0x2)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = repoSpanner localhost.localdomain cluster CA
        Validity
            Not Before: Nov 28 16:34:41 2018 GMT
            Not After : Nov 28 16:34:41 2019 GMT
        Subject: CN = pagure1.local.localhost.localdomain
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:99:9a:19:cd:9c:14:64:04:2b:19:b7:d3:bf:0d:
                    58:16:d7:bf:f5:97:02:d8:4f:fb:11:d6:c5:e2:0b:
                    62:26:87:53:f6:74:3d:0a:64:4b:30:3f:27:8f:21:
                    48:ba:5e:62:89:fc:99:b4:29:77:fc:3b:3b:43:a9:
                    31:f5:80:fe:a7:75:57:d8:95:24:2b:70:1d:60:94:
                    c4:ab:38:10:01:8f:af:3d:b9:aa:52:9c:1a:d3:2e:
                    81:8f:89:d5:fb:69:62:01:48:70:af:4d:31:55:6f:
                    0b:19:d8:62:5f:ec:f4:ab:50:66:19:cb:f1:17:e6:
                    65:82:7d:a8:af:01:e1:71:02:6c:ef:7c:62:0b:e2:
                    ce:81:51:66:a5:f3:9f:70:d6:35:4d:15:e3:ea:9a:
                    1a:59:9c:5f:cc:fd:0e:54:25:3f:e9:24:a6:2d:83:
                    7f:3f:57:a6:01:8b:33:48:6d:dc:56:c5:8d:28:46:
                    b7:0e:9f:f8:b2:68:96:64:a6:81:84:37:f8:85:e5:
                    02:a9:ef:60:f7:87:be:7a:20:97:4b:8d:e4:38:78:
                    c3:60:1f:e9:d6:d7:27:33:99:9d:3d:40:38:31:19:
                    e3:26:69:9e:79:f8:9b:06:58:17:1c:25:00:64:d1:
                    6d:65:39:95:de:f9:49:9e:e3:1e:a4:e2:88:02:d6:
                    59:ff
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE, pathlen:0
            X509v3 Subject Alternative Name: 
                DNS:pagure1.local.localhost.localdomain
            1.3.6.1.4.1.37476.9000.56.1.1: 
                localhost.localdomain
            1.3.6.1.4.1.37476.9000.56.1.2: 
                local
            1.3.6.1.4.1.37476.9000.56.1.3: 
                pagure1
            1.3.6.1.4.1.37476.9000.56.1.4: 
                2
    Signature Algorithm: sha256WithRSAEncryption
         8c:54:1f:0e:c6:ee:85:a3:4d:38:e1:98:28:37:e7:0a:9b:2e:
         6e:06:78:98:66:a0:7a:64:e2:9a:0a:4b:2a:6b:45:c4:ae:1d:
         3d:cd:01:55:1f:82:00:ad:92:25:31:8f:de:3f:ab:56:13:de:
         d9:c8:aa:79:36:14:fa:3a:b8:10:bf:f7:69:fe:fc:c3:19:c1:
         9c:77:dc:64:93:b7:67:f7:04:4e:21:d9:ea:79:5c:64:50:6c:
         ae:3c:c6:4d:e0:e1:ac:80:95:66:3f:cb:2f:91:8c:18:37:cf:
         da:95:ec:69:80:87:7a:67:db:f6:93:6a:63:15:17:54:3d:f1:
         cf:74:49:d8:d2:15:95:bf:21:d3:31:7b:27:ec:90:3c:b6:24:
         c0:e4:df:aa:6f:5a:77:bb:a7:8b:63:b0:6d:84:ec:d3:26:3b:
         26:6d:99:09:39:80:5c:1f:8c:1b:16:c6:34:dd:b7:14:af:64:
         7f:4f:37:09:90:ac:c8:b0:05:f4:5e:fd:db:dc:14:df:60:34:
         ab:ef:7c:4e:e9:2f:56:4b:a1:2c:2d:0b:8d:d2:f6:5d:c8:63:
         9b:08:71:a8:45:1b:db:58:9d:47:ad:db:8b:8d:9e:76:4a:6c:
         08:74:a3:39:31:eb:a2:8d:cd:b1:1b:f0:57:e2:d5:74:7e:a9:
         88:0b:6b:b9
```

I created this cert by using `repospanner ca leaf admin --admin --write --read --region "*" --repo "*"`

**Comment by puiterwijk** [comment]
You did not create this certificate in that way.
This certificate is a node certificate, with no access to the API or direct repository access in any way or form.
This was probably more like: `repospanner ca node local pagure1`.

**Comment by bkabrda** [comment]
Ah, you're right. So I need to use the admin certificate for this, right? I tried that just now, but got: `fatal: remote error: Error bridging request`. The node logs now contain this message:

```
time="2019-01-16T11:20:38Z" level=info msg="http: TLS handshake error from 172.18.0.1:43560: Incorrect region * found\n" depth=5 fields.level=INFO pkg=
```

Edit: looking at the code [1], I don't see how a wildcard could be supported. It seems that a strict string match is required for the region check to pass. Is wildcard supposed to work?

[1] https://github.com/repoSpanner/repoSpanner/blob/72a63494b55a2ef2af5f2245bd21833cc89a28c6/server/service/core.go#L329

**Comment by puiterwijk** [comment]
The code you linked to is for node certificate verifications: nodes are always in exactly one region.
Verification of the `*` string happens in authutils: https://github.com/repoSpanner/repoSpanner/blob/72a63494b55a2ef2af5f2245bd21833cc89a28c6/server/service/authutils.go#L66

The `Incorrect region * found` would mean that an attempt was made to communicate with the node port.
Now that I think about it, the fact that your node certificate was accepted from the start means that you are using the node interface.
The node port ("rpcport") is only used for node-to-node communications, you want to configure the bridge (and Pagure) to use the "http.port".

(I should probably make the bridge check against using a node certificate, will add that to my todo.)

**Comment by puiterwijk** [comment]
I just added a "ca info" command you can use to get information on a certificate in a user readable format in 262568df7091b232765c1d42ec3b3db2854f43b4.

**Comment by puiterwijk** [comment]
391f50be32ec2b0f126471ab4a71c40b598c9531 adds a check to verify the type of certificate passed to the bridge, and errors with a usable error message if it's not a leaf certificate.

**Comment by puiterwijk** [comment]
> Ah, you're right. So I need to use the admin certificate for this, right?

Just to comment on this: yes, and admin cert would work, but from a security point of view, it would be ideal to create a new certificate for the bridge and use that.
(just my paranoia ruling. I tried to make everything as resistant to "weird" or malicious input, but the bridge is still something called with direct user input :) )

**Comment by puiterwijk** [comment]
Also, do note that after commit fdc75a7c55719f93773ed7624a7fb35a2c66b866, the bridge will actually print what made it fail to bridge the request (in this case, it would've given a TLS handshake error probably).

**Comment by puiterwijk** [comment]
And commit 52e9e3782ab778334cad9f0d2d255b01c1c620e9 will make it so that if anyone again tries to send a leaf certificate to the Node interface, it errors out with an accurate error.

Thank you very much for the information on where I have made too many assumptions on what is simple and not, please do keep them coming! :)

**Comment by bkabrda** [comment]
Yeah, thanks for all the changes, these are really helpful. I think this issue can be closed now.

**Comment by puiterwijk** [comment]
Okay, thanks again for the feedback.
