### ISSUE TITLE
git fetch-pack fails

### ISSUE THREAD

**Issue by apevec** [repoSpanner/repoSpanner#61]
I'm testing a staging instance of repoSpanner at git.stg.centos.org

I was able to git clone one repository successfully but add git remote add + git fetch fails.

WORKS:
git clone ssh://git@git.stg.centos.org/forks/apevec/rpms/ansible.git
Cloning into 'ansible'...
remote: Welcome to repoSpanner 0.5+6.18a344a268dd1cd8801b22c03781dafbfdb10937.el7.infra, node centos01.rpms.stg.fedoraproject.org
Receiving objects: 100% (881/881), 746.49 KiB | 1.46 MiB/s, done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.

FAILS:
git remote add -f ap ssh://git@git.stg.centos.org/forks/apevec/rpms/ansible.git
Updating ap
fatal: git fetch-pack: expected ACK/NAK, got '?Welcome to repoSpanner 0.5+6.18a344a268dd1cd8801b22c03781dafbfdb10937.el7.infra, node centos01.rpms.stg.fedoraproject.org'

**Comment by puiterwijk** [comment]
Thanks for the report, this should be fixed in 19fa9ef2684964b3d4f7ee8ecdb5d768ced5a770 .
